---
title: "Developing Data Products Week 2 Assignment"
author: "Ann Bessenbacher"
date: "September 3, 2017"
output: html_document
---

```{r setvariable, echo=FALSE, warning=FALSE, message=FALSE}
library(leaflet)
library(geojson)
library(geojsonio)
url <- "http://leafletjs.com/examples/choropleth/us-states.js"

# read as text file
doc <- readLines(url)

# remove the javascript assignment at the front 
doc2 <- gsub("var statesData = ", "", doc)

# write out as a temp file and read
write(doc2, file = "tempgeo.json")
states <- geojson_read("tempgeo.json", what = "sp")
bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("viridis", domain = states$density, bins = bins)

r_colors <- rgb(t(col2rgb(colors()) / 255))
names(r_colors) <- colors()

## creating state labels
labels <- sprintf(
      "<strong>%s</strong><br/>%g people / mi<sup>2</sup>",
      states$name, states$density
    ) %>% lapply(htmltools::HTML)
```

## Interactive Leaflet Map
I chose to create a state level map showing population density because
this is the most applicable to what I'm currently working on.
Hint: Hover over states to see interactivity.

```{r createmap, echo=FALSE, warning=FALSE}
m <- leaflet(states) %>%
      setView(-96, 37.8, 4) %>%
      addTiles() %>%
      addPolygons(
        fillColor = ~pal(density),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto"))
    
    ## adding legend
    m %>% addLegend(pal = pal, values = ~density, opacity = 0.7, title = "Population Density",
                    position = "bottomright")


```


